apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    configmaps: "20" 
    persistentvolumeclaims: "4" 
    replicationcontrollers: "20" 
    secrets: "10" 
    services: "10" 
    services.loadbalancers: "2"
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "3"
    limits.memory: 6Gi
